Refactor erdjs-snippets
ElrondNetwork/elrond-lend-rs pull request #43
Opened 2022-05-12 08:55 UTC by CostinCarabas

* Add lendingPoolHelper to avoid duplication in lendingPool.spec
* Add code for Borrow System Test

2022-05-30 10:50 UTC, andreibancioiu requested changes

2022-05-30 10:50 UTC, andreibancioiu commented on erdjs-snippets/lending-pool/lendingPoolInteractor.ts
> +        let depositNonce: number = +(<Struct>firstValue).getFieldValue("token_nonce")["c"][0];
Perhaps `getFieldValue("token_nonce").toNumber()`?

2022-05-30 10:50 UTC, andreibancioiu commented on erdjs-snippets/lending-pool/lendingPoolInteractor.ts
> +        let borrowNonce: number = +(<Struct>firstValue).getFieldValue("token_nonce")["c"][0];
Perhaps `getFieldValue("token_nonce").toNumber()`?

2022-07-22 07:57 UTC, claudiu725 approved these changes

2022-07-22 10:57 UTC, merged