Add collateral feature
ElrondNetwork/elrond-lend-rs pull request #60
Opened 2022-07-14 21:44 UTC by CostinCarabas

Borrowers are able to add collateral to improve the borrow's health.
Add unit test

Issue: https://github.com/ElrondNetwork/elrond-lend-rs/issues/55

2022-07-14 21:45 UTC, CostinCarabas commented
![Add Collateral Scenario (1)](https://user-images.githubusercontent.com/3630188/179091539-b933014e-4ccc-4dd1-85e6-8ed58155afbd.png)

2022-07-21 17:20 UTC, virgil-serbanuta commented on liquidity_pool/src/liquidity.rs
> +            borrow_position.lend_tokens,
I just noticed that the borrow_position corresponds to the same nonce, which makes most of my previous comment useless.

However, note that `deposit_asset` generates a new nonce each time, which means that the `add_collateral` endpoint can be used only if the borrower didn't use all the initial lend_tokens as collateral when creating the debt, which limits its usefulness.

2022-07-22 10:57 UTC, CostinCarabas commented on liquidity_pool/src/liquidity.rs
> +            borrow_position.lend_tokens,
@virgil-serbanuta , 
Yep, I think it makes sense to make the LTokens fungible. This would solve the issue you described above.

2022-07-26 08:29 UTC, CostinCarabas commented on liquidity_pool/src/liquidity.rs
> +            borrow_position.lend_tokens,
We will make a redesign of the Lending SC to adjust the reported issue. For this PR, I will not solve this issue.

2022-07-26 11:22 UTC, claudiu725 requested changes

2022-07-28 09:26 UTC, claudiu725 approved these changes

2022-07-29 14:43 UTC, merged