Redesign Deposit and Borrow Positions
ElrondNetwork/elrond-lend-rs pull request #64
Opened 2022-08-19 13:20 UTC by CostinCarabas

Redesign DepositPositions and BorrowPosition to remove iter() due to performance penalties.

2022-08-22 08:21 UTC, claudiu725 requested changes

2022-08-23 06:09 UTC, CostinCarabas commented on lending_pool/src/lib.rs
> +            if let Some(dp) = deposit_positions.get(&token) {
Nice catch!

2022-08-25 05:48 UTC, alyn509 approved these changes

2022-08-25 10:44 UTC, claudiu725 approved these changes

2022-08-30 08:22 UTC, merged